# Generated by Django 3.2.1 on 2021-05-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='director',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='contents',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
